// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GooseDBVersion   string
	Messages         string
	Sessions         string
	Users            string
	Websites         string
	WebsitesMessages string
}{
	GooseDBVersion:   "goose_db_version",
	Messages:         "messages",
	Sessions:         "sessions",
	Users:            "users",
	Websites:         "websites",
	WebsitesMessages: "websites_messages",
}
