// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Invitation is an object representing the database table.
type Invitation struct {
	ID        int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	Email     string    `boil:"email" json:"email" toml:"email" yaml:"email"`
	Token     string    `boil:"token" json:"token" toml:"token" yaml:"token"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	InvitedBy int64     `boil:"invited_by" json:"invited_by" toml:"invited_by" yaml:"invited_by"`

	R *invitationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L invitationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var InvitationColumns = struct {
	ID        string
	Email     string
	Token     string
	CreatedAt string
	InvitedBy string
}{
	ID:        "id",
	Email:     "email",
	Token:     "token",
	CreatedAt: "created_at",
	InvitedBy: "invited_by",
}

var InvitationTableColumns = struct {
	ID        string
	Email     string
	Token     string
	CreatedAt string
	InvitedBy string
}{
	ID:        "invitation.id",
	Email:     "invitation.email",
	Token:     "invitation.token",
	CreatedAt: "invitation.created_at",
	InvitedBy: "invitation.invited_by",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod  { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var InvitationWhere = struct {
	ID        whereHelperint64
	Email     whereHelperstring
	Token     whereHelperstring
	CreatedAt whereHelpertime_Time
	InvitedBy whereHelperint64
}{
	ID:        whereHelperint64{field: "\"invitation\".\"id\""},
	Email:     whereHelperstring{field: "\"invitation\".\"email\""},
	Token:     whereHelperstring{field: "\"invitation\".\"token\""},
	CreatedAt: whereHelpertime_Time{field: "\"invitation\".\"created_at\""},
	InvitedBy: whereHelperint64{field: "\"invitation\".\"invited_by\""},
}

// InvitationRels is where relationship names are stored.
var InvitationRels = struct {
	InvitedByUser string
}{
	InvitedByUser: "InvitedByUser",
}

// invitationR is where relationships are stored.
type invitationR struct {
	InvitedByUser *User `boil:"InvitedByUser" json:"InvitedByUser" toml:"InvitedByUser" yaml:"InvitedByUser"`
}

// NewStruct creates a new relationship struct
func (*invitationR) NewStruct() *invitationR {
	return &invitationR{}
}

func (r *invitationR) GetInvitedByUser() *User {
	if r == nil {
		return nil
	}
	return r.InvitedByUser
}

// invitationL is where Load methods for each relationship are stored.
type invitationL struct{}

var (
	invitationAllColumns            = []string{"id", "email", "token", "created_at", "invited_by"}
	invitationColumnsWithoutDefault = []string{"email", "token", "created_at", "invited_by"}
	invitationColumnsWithDefault    = []string{"id"}
	invitationPrimaryKeyColumns     = []string{"id"}
	invitationGeneratedColumns      = []string{"id"}
)

type (
	// InvitationSlice is an alias for a slice of pointers to Invitation.
	// This should almost always be used instead of []Invitation.
	InvitationSlice []*Invitation
	// InvitationHook is the signature for custom Invitation hook methods
	InvitationHook func(context.Context, boil.ContextExecutor, *Invitation) error

	invitationQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	invitationType                 = reflect.TypeOf(&Invitation{})
	invitationMapping              = queries.MakeStructMapping(invitationType)
	invitationPrimaryKeyMapping, _ = queries.BindMapping(invitationType, invitationMapping, invitationPrimaryKeyColumns)
	invitationInsertCacheMut       sync.RWMutex
	invitationInsertCache          = make(map[string]insertCache)
	invitationUpdateCacheMut       sync.RWMutex
	invitationUpdateCache          = make(map[string]updateCache)
	invitationUpsertCacheMut       sync.RWMutex
	invitationUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var invitationAfterSelectMu sync.Mutex
var invitationAfterSelectHooks []InvitationHook

var invitationBeforeInsertMu sync.Mutex
var invitationBeforeInsertHooks []InvitationHook
var invitationAfterInsertMu sync.Mutex
var invitationAfterInsertHooks []InvitationHook

var invitationBeforeUpdateMu sync.Mutex
var invitationBeforeUpdateHooks []InvitationHook
var invitationAfterUpdateMu sync.Mutex
var invitationAfterUpdateHooks []InvitationHook

var invitationBeforeDeleteMu sync.Mutex
var invitationBeforeDeleteHooks []InvitationHook
var invitationAfterDeleteMu sync.Mutex
var invitationAfterDeleteHooks []InvitationHook

var invitationBeforeUpsertMu sync.Mutex
var invitationBeforeUpsertHooks []InvitationHook
var invitationAfterUpsertMu sync.Mutex
var invitationAfterUpsertHooks []InvitationHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Invitation) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range invitationAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Invitation) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range invitationBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Invitation) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range invitationAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Invitation) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range invitationBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Invitation) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range invitationAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Invitation) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range invitationBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Invitation) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range invitationAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Invitation) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range invitationBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Invitation) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range invitationAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddInvitationHook registers your hook function for all future operations.
func AddInvitationHook(hookPoint boil.HookPoint, invitationHook InvitationHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		invitationAfterSelectMu.Lock()
		invitationAfterSelectHooks = append(invitationAfterSelectHooks, invitationHook)
		invitationAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		invitationBeforeInsertMu.Lock()
		invitationBeforeInsertHooks = append(invitationBeforeInsertHooks, invitationHook)
		invitationBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		invitationAfterInsertMu.Lock()
		invitationAfterInsertHooks = append(invitationAfterInsertHooks, invitationHook)
		invitationAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		invitationBeforeUpdateMu.Lock()
		invitationBeforeUpdateHooks = append(invitationBeforeUpdateHooks, invitationHook)
		invitationBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		invitationAfterUpdateMu.Lock()
		invitationAfterUpdateHooks = append(invitationAfterUpdateHooks, invitationHook)
		invitationAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		invitationBeforeDeleteMu.Lock()
		invitationBeforeDeleteHooks = append(invitationBeforeDeleteHooks, invitationHook)
		invitationBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		invitationAfterDeleteMu.Lock()
		invitationAfterDeleteHooks = append(invitationAfterDeleteHooks, invitationHook)
		invitationAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		invitationBeforeUpsertMu.Lock()
		invitationBeforeUpsertHooks = append(invitationBeforeUpsertHooks, invitationHook)
		invitationBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		invitationAfterUpsertMu.Lock()
		invitationAfterUpsertHooks = append(invitationAfterUpsertHooks, invitationHook)
		invitationAfterUpsertMu.Unlock()
	}
}

// One returns a single invitation record from the query.
func (q invitationQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Invitation, error) {
	o := &Invitation{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for invitation")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Invitation records from the query.
func (q invitationQuery) All(ctx context.Context, exec boil.ContextExecutor) (InvitationSlice, error) {
	var o []*Invitation

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Invitation slice")
	}

	if len(invitationAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Invitation records in the query.
func (q invitationQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count invitation rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q invitationQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if invitation exists")
	}

	return count > 0, nil
}

// InvitedByUser pointed to by the foreign key.
func (o *Invitation) InvitedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.InvitedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadInvitedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (invitationL) LoadInvitedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeInvitation interface{}, mods queries.Applicator) error {
	var slice []*Invitation
	var object *Invitation

	if singular {
		var ok bool
		object, ok = maybeInvitation.(*Invitation)
		if !ok {
			object = new(Invitation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeInvitation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeInvitation))
			}
		}
	} else {
		s, ok := maybeInvitation.(*[]*Invitation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeInvitation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeInvitation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &invitationR{}
		}
		args[object.InvitedBy] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &invitationR{}
			}

			args[obj.InvitedBy] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.InvitedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.InvitedByInvitations = append(foreign.R.InvitedByInvitations, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.InvitedBy == foreign.ID {
				local.R.InvitedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.InvitedByInvitations = append(foreign.R.InvitedByInvitations, local)
				break
			}
		}
	}

	return nil
}

// SetInvitedByUser of the invitation to the related item.
// Sets o.R.InvitedByUser to related.
// Adds o to related.R.InvitedByInvitations.
func (o *Invitation) SetInvitedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"invitation\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"invited_by"}),
		strmangle.WhereClause("\"", "\"", 0, invitationPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.InvitedBy = related.ID
	if o.R == nil {
		o.R = &invitationR{
			InvitedByUser: related,
		}
	} else {
		o.R.InvitedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			InvitedByInvitations: InvitationSlice{o},
		}
	} else {
		related.R.InvitedByInvitations = append(related.R.InvitedByInvitations, o)
	}

	return nil
}

// Invitations retrieves all the records using an executor.
func Invitations(mods ...qm.QueryMod) invitationQuery {
	mods = append(mods, qm.From("\"invitation\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"invitation\".*"})
	}

	return invitationQuery{q}
}

// FindInvitation retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindInvitation(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Invitation, error) {
	invitationObj := &Invitation{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"invitation\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, invitationObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from invitation")
	}

	if err = invitationObj.doAfterSelectHooks(ctx, exec); err != nil {
		return invitationObj, err
	}

	return invitationObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Invitation) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no invitation provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(invitationColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	invitationInsertCacheMut.RLock()
	cache, cached := invitationInsertCache[key]
	invitationInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			invitationAllColumns,
			invitationColumnsWithDefault,
			invitationColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, invitationGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(invitationType, invitationMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(invitationType, invitationMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"invitation\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"invitation\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into invitation")
	}

	if !cached {
		invitationInsertCacheMut.Lock()
		invitationInsertCache[key] = cache
		invitationInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Invitation.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Invitation) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	invitationUpdateCacheMut.RLock()
	cache, cached := invitationUpdateCache[key]
	invitationUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			invitationAllColumns,
			invitationPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, invitationGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update invitation, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"invitation\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, invitationPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(invitationType, invitationMapping, append(wl, invitationPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update invitation row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for invitation")
	}

	if !cached {
		invitationUpdateCacheMut.Lock()
		invitationUpdateCache[key] = cache
		invitationUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q invitationQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for invitation")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for invitation")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o InvitationSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), invitationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"invitation\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, invitationPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in invitation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all invitation")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Invitation) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no invitation provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(invitationColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	invitationUpsertCacheMut.RLock()
	cache, cached := invitationUpsertCache[key]
	invitationUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			invitationAllColumns,
			invitationColumnsWithDefault,
			invitationColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			invitationAllColumns,
			invitationPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert invitation, could not build update column list")
		}

		ret := strmangle.SetComplement(invitationAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(invitationPrimaryKeyColumns))
			copy(conflict, invitationPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"invitation\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(invitationType, invitationMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(invitationType, invitationMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert invitation")
	}

	if !cached {
		invitationUpsertCacheMut.Lock()
		invitationUpsertCache[key] = cache
		invitationUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Invitation record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Invitation) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Invitation provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), invitationPrimaryKeyMapping)
	sql := "DELETE FROM \"invitation\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from invitation")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for invitation")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q invitationQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no invitationQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from invitation")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for invitation")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o InvitationSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(invitationBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), invitationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"invitation\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, invitationPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from invitation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for invitation")
	}

	if len(invitationAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Invitation) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindInvitation(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *InvitationSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := InvitationSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), invitationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"invitation\".* FROM \"invitation\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, invitationPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in InvitationSlice")
	}

	*o = slice

	return nil
}

// InvitationExists checks if the Invitation row exists.
func InvitationExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"invitation\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if invitation exists")
	}

	return exists, nil
}

// Exists checks if the Invitation row exists.
func (o *Invitation) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return InvitationExists(ctx, exec, o.ID)
}
