name: Publish

on:
  push:
    tags:
      - "v*.*.*" # Matches tags like v1.0.0, v2.1.3, etc.

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22.4"

      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6

      - run: ko build cmd/app/main.go
